name: Print Messages on Pull Request

on:
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  print_messages:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment Variable
        run: echo "Environment Variable: ${{ env.MY_ENV_VAR }}"
        env:
          MY_ENV_VAR: "This is an environment variable"

      - name: Print Secret
        run: echo "Secret: ${{ secrets.MY_SECRET }}"
